import 'package:flutter/material.dart';

/* 

vegetables : 1
meat : 2
Gatas : 3
sugar : 4
fruit : 5
rice : 6
fat : 7


 */

final Map<String, Map<String, Map<String, dynamic>>> itemMacronutrients = {
  'Alimango': {
    '1 Tbsp Alige': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Pc Laman': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Alimasag': {
    '1 & 1/2 Tbsps Alige': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Laman': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Alimuran': {
    '13 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Ampaw (Kanin)': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Apas': {
    '7 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Arnibal': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Asukal': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Atis': {
    '1 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 5,
    },
  },
  'Avocado': {
    '1 Pc': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1/2 Pc': {
      'fats': 3,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 7,
    },
  },
  'Bacon': {
    '1 Strip/Pc': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Balat ng Lumpia': {
    '7 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Balatan': {
    '6 Pcs': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Balimbing': {
    '4 & 1/2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Banana Chips': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Bayabas (Pula)': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Beef': {
    '1 Slice Kenchi': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Laman': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Round Hita': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Lomo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tagiliran (Gitna)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tagiliran (Hulihan)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Camto': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tadyang': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Paypay/Laman': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Punta y Pecho': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Beef Tallow': {
    '1 Tsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Bibingka': {
    '1/2 Slice Galapong': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Slice Malagkit': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Pinipig': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Bignay': {
    '2 Cups': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Binatog': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Blueberries': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Boiled Egg': {
    //check
    'Whole Egg (Chicken)': {
      'fats': 5,
      'carbs': 1,
      'proteins': 6,
      'foodExchange': 1,
      'type': 8,
    },
    'Half Egg (Chicken)': {
      'fats': 3,
      'carbs': 0,
      'proteins': 3,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'Brohas': {
    '5 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Bukayo': {
    '1 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Cake (Mamon/Tostado)': {
    '3 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Camachili': {
    '7 Pods': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Candy': {
    '1 Pc': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Tira-tira': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '2 Pcs Sampalok': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Caramel/Hard/Toffee': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Carabeef': {
    '1 Slice Kenchi': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Laman (May Bahagyang Taba)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Hita': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Laman (May Katamtamang Taba)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Paypay': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Pierna Corta at Piena Larga': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tapadera': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Champoy': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Cheese': {
    '1/3 Cup Cottage': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Cheddar (Processed)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/3 Cup Feta': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 & 1/2 Slices Gouda': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Parmesan (Grated)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 & 1/2 Tbsps  Pimiento': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Keso de Bola': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Cherries (Hinog)': {
    '7 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Cherry (Syrup)': {
    '5 Pcs': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Chewing Gum': {
    '1-2 Pcs': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Chico': {
    '1 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Chicken (Adobong Iga)': {
    //check
    //Case 1: Warning lang na kapag sobra sa oil nung luto bawal dito (hyper, obesity, diabetes)
    //Case 2: Warning if matamis yung luto bawal sa may diabetes
    'Whole Cup': {
      'fats': 16,
      'carbs': 8,
      'proteins': 16,
      'foodExchange': 1,
      'type': 8,
    },
    'Half Cup': {
      'fats': 8,
      'carbs': 4,
      'proteins': 8,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'Chicken (Chicken Inasal)': {
    //check
    'Breast with Wings': {
      'fats': 27,
      'carbs': 13,
      'proteins': 27,
      'foodExchange': 1,
      'type': 8,
    },
    'Leg': {
      'fats': 21,
      'carbs': 13,
      'proteins': 24,
      'foodExchange': 1,
      'type': 8,
    },
    'Thigh': {
      'fats': 10,
      'carbs': 5,
      'proteins': 20,
      'foodExchange': 1,
      'type': 8,
    },
    'Drumstick': {
      'fats': 13,
      'carbs': 7,
      'proteins': 17,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Chicken (Fried Chicken)': {
    //check
    'Drumstick': {
      'fats': 7,
      'carbs': 0,
      'proteins': 14,
      'warnings': 2,
      'foodExchange': 1,
      'type': 8,
    },
    'Breast': {
      'fats': 9,
      'carbs': 0,
      'proteins': 31,
      'warnings': 2,
      'foodExchange': 1,
      'type': 8,
    },
    'Leg': {
      'fats': 17,
      'carbs': 0,
      'proteins': 31,
      'warnings': 2,
      'foodExchange': 1,
      'type': 8,
    },
    'Thigh': {
      'fats': 10,
      'carbs': 0,
      'proteins': 17,
      'warnings': 2,
      'foodExchange': 1,
      'type': 8,
    },
    'Wing': {
      'fats': 7,
      'carbs': 0,
      'proteins': 9,
      'warnings': 2,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Coco Sugar': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Coco Syrup': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Chocolate': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Cookies': {
    '8 Pcs Marie': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '7 Pcs Pasencia': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Corn Flakes': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Corn Products': {
    '1/4 Cup Cornstarch': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Slice Maja Blanca': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Maja Mais': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Cream Cheese': {
    '1 Tbsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  /* 'Cream': {
    '1 Tbsp All Purpose': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tbsp Fluid (Heavy/Light)': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '4 Tsps Krema': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  }, */
  'Cuapao': {
    '1/2 Pc': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Dalagang Bukid (Golden)': {
    '1/2 Pc': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Dalandan': {
    '1 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 5,
    },
  },
  'Dates': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Dates (Pitted)': {
    '1 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Datiles': {
    '1/2 Cup / 25 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Dikyam': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Dragon Fruit': {
    '1/2 Cup / 1/4 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Duhat': {
    '12 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Dulce de Leche': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Durian': {
    '2 Segments': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Egg': {
    '1 Pc Medium (Chicken Buo)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Medium (Pato Buo)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '7 Pcs Maliit Pugo': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Balut': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Penoy': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Pato (Buo)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Espasol': {
    '1 Slice': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Fish (Daing na Bangus)': {
    //check
    'Big - 1 Slice': {
      'fats': 12,
      'carbs': 1,
      'proteins': 22,
      'foodExchange': 1,
      'type': 8,
    },
    'Small - 1 Slice': {
      'fats': 5,
      'carbs': 0,
      'proteins': 13,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'Fish (Pan Fried Tilapia)': {
    //check
    'Head': {
      'fats': 3,
      'carbs': 6,
      'proteins': 8,
      'foodExchange': 1,
      'type': 8,
    },
    'Body': {
      'fats': 10,
      'carbs': 17,
      'proteins': 25,
      'foodExchange': 1,
      'type': 8,
    },
    'Tail': {
      'fats': 3,
      'carbs': 6,
      'proteins': 8,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Fish (Sinaing na Tulingan)': {
    //check
    'Head': {
      'fats': 4,
      'carbs': 0,
      'proteins': 7,
      'foodExchange': 1,
      'type': 8,
    },
    'Body': {
      'fats': 13,
      'carbs': 1,
      'proteins': 22,
      'foodExchange': 1,
      'type': 8,
    },
    'Tail': {
      'fats': 4,
      'carbs': 0,
      'proteins': 7,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Fish': {
    '1/2 Pc Karpa': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Pc Alumahan (Striped)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Pc Bakokong Moro': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Bangus': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Dalag (Striated)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/3 Cup Dilis (Buo)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Dilis (Walang Ulo)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Cup Dulong': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Galunggong': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Hasa-hasa': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Hito': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Labahita': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Lapu-lapu': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Matang Baka': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Sapsap': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Saramulyete': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Tambakol': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 & 1/2 Pcs Tamban': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Tawilis': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Tilapia': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Slice Tulingan': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Fish (Daing)': {
    '8 Pcs Alakaak': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Alumahan': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/3 Pc Bakalaw': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Bisugo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Malaki / 11 Pcs Maliit Biyang Puti': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Lapu-lapu': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3 & 1/2 Pcs Malasugi': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '7 Pcs Sapsap': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Tamban': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Tilapia': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Fish (De Lata)': {
    '3 Slices Salmon sa Mantika': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3 Pcs Sardinas (Spanish Style)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Sardinas sa Kamatis': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Tuna Flakes ': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Tuna Flakes (In Brine)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Tbsps Tuna Spread': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Fish (Tinapa)': {
    '1/2 Pc Galunggong': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3 Pcs Tamban': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3 Pcs Tunsoy': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Bangus': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
  },
  'Fish (Tuyo)': {
    '1/2 Cup Alamang': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '13 Pcs Dilis': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '4 Tbsps Hibe': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Pusit': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '4 Pcs Sapsap': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Tamban': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Gabi (Cubed)': {
    '3/4 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Gatas': {
    '3/4 Cup Buttermilk': {
      'carbs': 12,
      'proteins': 8,
      'fats': 0,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Tsp Sweetened': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Tsp Kondensada': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Tsp Filled': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '3/4 Cup Kalabaw': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Cup Baka': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '1/2 Cup Evaporada': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '1/2 Cup Evaporada Filled': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Cup Kambing': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '3/4 Cup Recombined': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '5 Tbsps Pulbos Filled Instant': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '5 Tbsps Pulbos Full cream': {
      'carbs': 12,
      'proteins': 8,
      'fats': 10,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Cup Low Fat': {
      'carbs': 12,
      'proteins': 8,
      'fats': 5,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Cup Skim': {
      'carbs': 12,
      'proteins': 8,
      'fats': 0,
      'foodExchange': 1,
      'type': 3,
    },
    '4 Tbsps Powder Skim': {
      'carbs': 12,
      'proteins': 8,
      'fats': 0,
      'foodExchange': 1,
      'type': 3,
    },
    '4 Tbsps Pulbos Non-Fat Instant': {
      'carbs': 12,
      'proteins': 8,
      'fats': 0,
      'foodExchange': 1,
      'type': 3,
    },
  },
  'Goat/Chevon': {
    '1 Slice Balikat': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Binti': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Biyas': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tiyan': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Dibdib': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Leeg': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Likod': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Lomo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Tadyang': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Granada': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Guava (Puti)': {
    '3 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Gulaman (Lasang Prutas)': {
    '1 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Gulay (De Lata)': {
    '1 Cup  Asparagus': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '2 Pcs Mais/Mura': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1 Tbsp Garbansos': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1 Tbsp Gisantes (Frozen)': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '2 Tbsps Mixed Vegetables (Carrot/Peas/Corn)': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '3/4 Cup Kabute': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '3 Tbsps Kamatis': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1/4 Cup Tomato Juice': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '4 Pcs Apulid': {
      'fats': 0,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
  },
  'Guyabano': {
    '1 Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Hipon': {
    'Alamang': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Pc Sugpo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '4 Pcs Suwahe': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Hopyang Hapon': {
    '1 Pc': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Internal Organs': {
    '1/4 Cup Atay': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Baga': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Balun-balunan': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Cup Bato': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Bitukang Maliit': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Sticks Bituka (Manok)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Dugo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Cup Lapay': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/2 Cup Librilyo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Litid': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Puso': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Bituka Maliit (Carabeef)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3/4 Cup Goto (Beef)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Utak (Pork, Beef, Carabeef)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Dila (Pork, Beef)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1/4 Cup Isaw ng Baboy (Maliit, Barbeque)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '7 Pcs Manok Puso': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Pork Tenga (Barbeque)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Itik': {
    '1 Pc Pakpak': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Hita': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Likod': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Dibdib': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Jam': {
    '2 Tsps': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Kalamay': {
    '1 Slice May Latik': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Ube': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Kamatis': {
    //check
    '1 Cup Diced': {
      'fats': 0,
      'carbs': 16,
      'proteins': 4,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup Diced': {
      'fats': 0,
      'carbs': 8,
      'proteins': 2,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Kamote': {
    '1 Pc / 3/4 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Kamoteng Kahoy': {
    '1 Slice (3/4 Cup) Cubed Balinghoy': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Bibingka': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Linupak': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Pichi-pichi': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Suman': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Kastanyas (Binusa)': {
    '8 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Kasuy': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Kayminto': {
    '1/2 Pc Berde': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Purple': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Kiamoy': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Kiwifruit': {
    '1 Pc Berde': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Berde': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 5,
    },
  },
  'Kuhol': {
    '12 Pcs': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Langka (Buto)': {
    '14 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Langka (Hinog)': {
    '1 & 1/2 Segments': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Lansones': {
    '5 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Lard': {
    '1 Tsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Latik': {
    '2 Tsps': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Lechiyas': {
    '4 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Longan': {
    '13 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Lapas': {
    '3 Pcs': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Leche Flan': {
    '1 Slice': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Lokum': {
    '1 Pc': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Lugaw': {
    '4 & 1/2 Cups Thin Consistency': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '3 Cups Medium Consistency': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 & 1/2 Cups Thick Consistency': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Mabolo': {
    '1/2 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Mais': {
    '1 Cup Butil (De Lata)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Cup Creamy Style (De Lata)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Mais (Dilaw & Puti)': {
    '1 Cup Durog': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Busal': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Makopa': {
    '9 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Mangga': {
    '1/2 Cup / 1 Pc Indyan Hilaw': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Cup / 1 Slice Kalabaw Hilaw': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Cup / 1 Slice Kalabaw Manibalang': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Cup / 1 Slice Kalabaw Hinog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '9 Pcs Paho Hilaw': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Slice Piko Hilaw': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Slice Piko Hinog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Slice Piko Manibalang': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Pc Supsupin Hinog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '2 Pcs Chips': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Mangosteen': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Manok': {
    '1 Pc Binti': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Hita': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Pakpak': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Ulo': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Chick (One-Day-Old/Fried)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '4 Pcs Manok Paa (Barbecue)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '3 Pcs Manok Ulo (Barbecue)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Manok (Puting Laman)': {
    '1 Slice Puting Laman': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Dibdib': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Marang': {
    '10 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '3/4 Cup / 1 Slice Honey Dew': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 & 1/4 Cups / 1 Slice Kastila': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 & 1/4 Cups / 1 Slice Tagalog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Margarine': {
    '1 Tsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Marshmallow': {
    '3 Pcs': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Mansanas': {
    '1 Pc Berde': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Pc Pula': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Mantekilya': {
    '1 Tsp Mantekilya': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '2 Tsps Mantekilya Light': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Matamis na Bao': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Mayonnaise': {
    '1 Tsp Mayonnaise': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '4 Tsps Mayonnaise Diet': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tbsp Mayonnaise Light': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Meat Products': {
    '1/4 Cup Karne Norte (De Lata)': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Sausages/Ham': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Pc Sausage (Chorizo)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 & 1/2 Pcs Sausages (Frankfurter)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs Sausage (Salami)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Mollusks': {
    '1/3 Cup Batotoy': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '22 Pcs Tuway ': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Nata de Coco': {
    '1 Tbsp': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Nilagang Ampalaya': {
    //check
    '1 Cup': {
      'fats': 4,
      'carbs': 5,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 2,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Broccoli': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 4,
      'proteins': 2,
      'foodExchange': 1,
      'type': 1,
    },
  },
  'Nilagang Carrot': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 13,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 0,
      'carbs': 7,
      'proteins': 1,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Kabute': {
    //check
    '1 Cup': {
      'fats': 1,
      'carbs': 8,
      'proteins': 3,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 0,
      'carbs': 4,
      'proteins': 2,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Kalabasa': {
    //check
    '1 Cup': {
      'fats': 1,
      'carbs': 5,
      'proteins': 2,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 1,
      'carbs': 3,
      'proteins': 1,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Kangkong': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 12,
      'proteins': 4,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 0,
      'carbs': 6,
      'proteins': 2,
      'foodExchange': .5,
      'type': 1,
    },
  },
  'Nilagang Mais': {
    //check
    '1 Maliit': {
      'fats': 1,
      'carbs': 19,
      'proteins': 3,
      'foodExchange': 1,
      'type': 1,
    }, //(5-6 inches long)
    '1 Medium': {
      'fats': 2,
      'carbs': 22,
      'proteins': 4,
      'foodExchange': 1,
      'type': 1,
    }, //(7 inches long)
    '1 Large': {
      'fats': 2,
      'carbs': 25,
      'proteins': 4,
      'foodExchange': 1,
      'type': 1,
    }, //(8-9 inches long)
    '1 Cup': {
      'fats': 2,
      'carbs': 31,
      'proteins': 5,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 1,
      'carbs': 16,
      'proteins': 3,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Okra': {
    //check
    '1 Cup': {
      'fats': 4,
      'carbs': 10,
      'proteins': 4,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup': {
      'fats': 2,
      'carbs': 5,
      'proteins': 2,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Nilagang Talong': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 9,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    }, //(1 inch per Pcs in the Cup)
    '1/2 Cup': {
      'fats': 0,
      'carbs': 5,
      'proteins': 1,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Niyog': {
    '1 Tbsp Kakang Gata': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '4 Tsps Magulang': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Noodles at Pasta': {
    '1 Cup Bihon': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Cup Misua': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Cup Sotanghon': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Cup Sweet Potato Noodles': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Nuts/Bean Products': {
    '7 Pcs Almond': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1/2 Cup Tofu': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
    '1 Pc Tokwa': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
    '5 Pcs Macadamia': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tbps Mixed Nuts': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '2 Tbsps Mani (May Balok/Binusa)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
    '2 Tbsps Mani (Walang Balok/Binusa)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
    '6 Pcs Kasuy (Binusa)': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '5 Pcs Pili Nuts': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '2 Pcs Walnut': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Orange': {
    '1/2 Pc Florida': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '3 Pcs Kiat Kiat': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Pc Ponkan': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Pakaskas (Panocha)': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Pakwan': {
    '1 Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Palaka (Laman)': {
    '1 Pc (Malaki)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '2 Pcs (Maliit)': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Palitaw (Walang niyog)': {
    '3 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Pampalamig na Inumin': {
    '1/2 Cup Lemon juice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Cup Tubig Niyog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/3 Cup Orange juice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/4 Cup Passion Fruit Juice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '4 Tbsps Apple Sauce (Sweetened)': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Cup Apple Sauce (Unsweetened)': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/4 Cup / 9 Pcs Blackberries Heavy Syrup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/4 Cup / 29 Pcs Blueberries Light Syrup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/4 Cup Fruit Cocktail': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '4 Pcs Lychee Syrup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Pc Peach Halves in Heavy Syrup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/3 Cup Pineapple (Crushed/Tidbits/Chunks)': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1 Ring Pineapple Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '3/4 Cup / 26 Pcs Strawberries (Unsweetened)': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/4 Cup / 7 Pcs Strawberries Heavy Syrup': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Papaya (Hinog)': {
    '3/4 Cup / 1 Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Pasas': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Pasta (Enriched/Unenriched)': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Pastilyas': {
    '1 Pc Durian': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Gatas': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Jackfruit': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Passion Fruit': {
    '1/4 Cup / 2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Peanut Butter': {
    '1 Tbsp': {
      'fats': 10,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1.5,
      'type': 7,
    },
    '1/2 Tbsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Peras': {
    '3/4 Cup / 1/2 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Persimon': {
    '1/2 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Pianono': {
    '1 Slice': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Pinya': {
    '1/2 Cup / 1 Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Pipino': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 4,
      'proteins': 0,
      'foodExchange': 1,
      'type': 1,
    },
  },
  'Plantains': {
    '1 Pc': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Pork (Breaded Pork Chop)': {
    //1 Slice ng tenderloin
    //Warning lang na iwasan yung matatabang part (para sa lahat ng sakit toh hyper, obesity, diabetes)
    '1 Slice': {
      'fats': 26,
      'carbs': 19,
      'proteins': 30,
      'warnings': 4,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Pork (Lechon Kawali)': {
    //1 Cup cooked, diced
    //Warning lang na iwasan yung matatabang part (para sa lahat ng sakit toh hyper, obesity, diabetes)
    'Whole Cup': {
      'fats': 37,
      'carbs': 4,
      'proteins': 25,
      'warnings': 4,
      'foodExchange': 1,
      'type': 8,
    },
    'Half Cup': {
      'fats': 19,
      'carbs': 2,
      'proteins': 13,
      'warnings': 4,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'Pork (Pork Bistek)': {
    //1 Slice ng tenderloin
    //Warning lang na iwasan yung matatabang part (para sa lahat ng sakit toh hyper, obesity, diabetes)
    'Pork Chop': {
      'fats': 7,
      'carbs': 3,
      'proteins': 26,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Pork Crackling (Skin)': {
    '5 Pcs': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '3 Pcs': {
      'fats': 3,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 7,
    },
  },
  'Pork ': {
    '1 Slice Kasim': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Liempo (Malaman)': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Pigi': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Ekstrang Tadyang': {
      'fats': 10,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Lomo': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
    '1 Slice Pata': {
      'fats': 6,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Potato': {
    //check
    '1 Cup Diced': {
      'fats': 0,
      'carbs': 26,
      'proteins': 3,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup Diced': {
      'fats': 0,
      'carbs': 13,
      'proteins': 2,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Prunes': {
    '1 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Pulot-pukyutan': {
    '1 Tsp': {
      'fats': 0,
      'carbs': 7,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Puto': {
    '1/2 Slice Puto Brown': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '2 Pcs Puto Bumbong': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Slice Puto Maya': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice / 3-4 Pcs Puto Puti': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '4 Pcs Puto Seko': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '7 Pcs Puto Seko (May Niyog)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Pusit': {
    '2 Pcs': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Quinoa': {
    '1 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Rambutan': {
    '5 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Rice Products': {
    '1/3 Cup Kanin (Protein Reduced)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '2 Pcs Ampaw (Pinipig)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Biko': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '2 Pcs Cuchinta': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Slice Sapin-sapin': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Saging': {
    '1/2 Pc Bungulan': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Cavendish Hinog': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Gloria': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Lakatan': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Latundan': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Murado': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
    '1/2 Pc Saba': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Sago Nilaga': {
    '1/2 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Sago Tapioca': {
    '1/4 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Salad Dressing': {
    '2 Tsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tsp': {
      'fats': 3,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 0.5,
      'type': 7,
    },
  },
  'Sampalok (Hinog)': {
    '12 Segments': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Sandwich Spread': {
    '1 Tbsp': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Santol': {
    '1 Pc': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Scrambled Egg': {
    //check
    '1 Pc Chicken Egg': {
      'fats': 7,
      'carbs': 1,
      'proteins': 6,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Seeds': {
    '1 Tbsp Sunflower': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '5 Pcs Patani': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '2 & 1/2 Tsps Flaxseed': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tbsp Kalabasa': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 Tbsp Linga': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
    '1 & 1/2 Tbsps Pakwan ': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Sibuyas': {
    //check
    '1 Cup Diced': {
      'fats': 0,
      'carbs': 16,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
    '1/2 Cup Diced': {
      'fats': 0,
      'carbs': 8,
      'proteins': 1,
      'foodExchange': 0.5,
      'type': 1,
    },
  },
  'Sinaing': {
    '1/2 Cup Puti': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Cup Mapula': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Cup Pinawa': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Singkamas (Ugat)': {
    '1 Cup / 1 & 1/2 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Siniguwelas': {
    '4 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Sour Cream': {
    '5 Tsps': {
      'fats': 5,
      'carbs': 0,
      'proteins': 0,
      'foodExchange': 1,
      'type': 7,
    },
  },
  'Sponge Cake': {
    '1 Slice': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Strawberry': {
    '1 & 1/4 Cups': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Suha': {
    '2 Segments': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Suman': {
    '1 Pc May Niyog': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Ibos': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Lihiya': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Sunny Side Up Egg': {
    //check
    '1 Pc Chicken Egg': {
      'fats': 7,
      'carbs': 0,
      'proteins': 6,
      'foodExchange': 1,
      'type': 8,
    },
  },
  'Taho': {
    '1/4 Cup': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Talangka': {
    '6 Pcs': {
      'fats': 1,
      'carbs': 0,
      'proteins': 8,
      'foodExchange': 1,
      'type': 2,
    },
  },
  'Talbos ng Kamote (Nilagang)': {
    //check
    '1 Cup': {
      'fats': 0,
      'carbs': 2,
      'proteins': 1,
      'foodExchange': 1,
      'type': 1,
    },
  },
  'Tamales': {
    '2 Pcs': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Tiesa': {
    '1/4 Pc / 1 Slice': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Tikoy': {
    '1 Slice': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Tinapay': {
    '1 & 1/2 Pcs Wheat': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Ensaymada': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Hamburger Bun': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Hotdog Roll': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '2 Pcs Loaf': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 & 1/2 Pcs Pan de Bonete': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pan de Leche': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Pc Pan de Limon': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pan de Monay': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pan de Sal': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pinagong': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pita Puti': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1/2 Pc Pita Bread (Whole)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '5 Pcs Tustado': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
    '1 Cup Couscous': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Tortang Talong': {
    //check
    '1 Eggplant': {
      'fats': 13,
      'carbs': 13,
      'proteins': 9,
      'foodExchange': 1,
      'type': 1,
    },
  },
  'Tugi': {
    '1 & 1/4 Cups (Cubed)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Tupig': {
    '1 Pc': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Tuyong Prutas': {
    '1 Pc Jackfruit': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Kiwi': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Mangga': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '1 Pc Papaya Chunks': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
    '2 Pcs Pineapple': {
      'fats': 0,
      'carbs': 5,
      'proteins': 0,
      'foodExchange': 1,
      'type': 4,
    },
  },
  'Ubas': {
    '12 Pcs': {
      'fats': 0,
      'carbs': 10,
      'proteins': 0,
      'foodExchange': 1,
      'type': 5,
    },
  },
  'Ube': {
    '1 Cup (Cubed)': {
      'fats': 0,
      'carbs': 23,
      'proteins': 0,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'Udon': {
    '1 Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 4,
      'foodExchange': 1,
      'type': 6,
    },
  },
  'White Rice (Boiled Rice)': {
    //check
    'Whole Cup': {
      'fats': 0,
      'carbs': 45,
      'proteins': 4,
      'foodExchange': 1,
      'type': 8,
    },
    'Half Cup': {
      'fats': 0,
      'carbs': 23,
      'proteins': 2,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'White Rice (Fried Rice)': {
    //check
    'Whole Cup': {
      'fats': 4,
      'carbs': 45,
      'proteins': 6,
      'foodExchange': 1,
      'type': 8,
    },
    'Half Cup': {
      'fats': 2,
      'carbs': 23,
      'proteins': 3,
      'foodExchange': 0.5,
      'type': 8,
    },
  },
  'Yogurt': {
    '1 Cup': {
      'fats': 10,
      'carbs': 24,
      'proteins': 16,
      'foodExchange': 1.5,
      'type': 3,
    },
    '1/2 Cup': {
      'fats': 5,
      'carbs': 12,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
  },
  'Yogurt (Non-fat)': {
    '1 Cup': {
      'fats': 0,
      'carbs': 25,
      'proteins': 16,
      'foodExchange': 1.5,
      'type': 3,
    },
    '1/2 Cup': {
      'fats': 0,
      'carbs': 12,
      'proteins': 8,
      'foodExchange': 1,
      'type': 3,
    },
  },
  'Yogurt (Plain Skim)': {
    '1/2 Cup': {
      'carbs': 12,
      'proteins': 8,
      'fats': 0,
      'foodExchange': 1,
      'type': 3,
    },
  },
};
